# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6633bdac0fcb1d609df04afc6528a5ed4505c440ad5f67c07e9b167fb67db152c322aebb0a8e5ad97dce9892a37a49997b2e050532aa15189850237add31437f

test:
  secret_key_base: 544813b063a9ce4d191c39a4942a181693c64546ecdece0eb9f31417c76f2be5214e284ed80fc9dda0b9e8462926da9ad140a700bbbb6bf2a1587f214513f802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 70dc277fe1c34b6b8002f029877d8f67b13cd33970dee2569d20139e55a8075a6be13c965c31ef0ed468fd944c1d0217f70422c2cc01267e91c853d5c7c787d7
